version: '3'
services:
  db:
    image: postgres:latest
    restart: always
    environment: 
      POSTGRES_PASSWORD: postgres
    ports:
      - "15432:5432"
    
  web:
    build: .
    depends_on: 
      - db
    expose: 
      - "8080"
      
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - web
    ports:
      - "8080:8080"